### ISSUE TITLE
[Wiki] It's not clear how someone loads the extension in Chrome

### ISSUE THREAD

**Issue by mattkennedynz** [twingl/trailblazer-wash#135]
From [a recent bit of feedback](https://github.com/twingl/trailblazer-wash/pull/134#issuecomment-255529762) about setting up a development environment:

> The only thing that throw me off at first was:
> `Visit chrome://extensions and turn on "developer mode" - this will allow you to load what's called an unpacked extension; the code you've just built.`
> Which I thought to mean loading the build/ folder. I figured it after a while out because the manifest file was in the root folder. Otherwise it was easy to follow.¨

The section referenced is under the heading [Load the extension in Chrome](https://github.com/twingl/trailblazer-wash/wiki/Getting-Started#load-the-extension-in-chrome) (contained in the Getting Started guide).

Suggested expansions:
- A slight elaboration of what turning developer mode "on" involves (i.e. checking the checkbox in the top corner).
- An explanation about which folder to select from the "Load unpacked extension" screen (i.e. needing only to select the root `trailbler-wash` folder on the contributor's machine).

**Comment by glsignal** [comment]
I've written a bit of an update to that section and elaborated on the setup instructions - feedback appreciated :)

**Comment by mattkennedynz** [comment]
Perfect—very well done ol' sport! ✨
